<script setup>
import {computed,ref} from 'vue';
const cats=['Все категории','Кофейни и рестораны','Салоны красоты и барбершопы','Магазины одежды','Магазины обуви','Фитнес и спорт','Спортивные секции','Образовательные центры','Языковые школы','Детские центры','Стоматологии','Медицинские центры','Автосервисы','Клининговые компании','Фотостудии','Ювелирные магазины','Риелторские агентства','Турагентства','Ветеринарные клиники','Зоомагазины','Ремонт техники','Творческие студии','Другие услуги'];
const city=ref('Алматы'),category=ref('Все категории'),onlyNoSite=ref(true),minRating=ref(0),limit=ref(30),leads=ref([]),loading=ref(false),checking=ref(false),generating=ref(false),error=ref(''),info=ref(''),selected=ref(null);
const shown=computed(()=>leads.value.filter(x=>(!onlyNoSite.value||!x.website)&&Number(x.rating||0)>=Number(minRating.value)));
async function search(){loading.value=true;error.value='';try{let p=new URLSearchParams({city:city.value,category:category.value,limit:limit.value});let r=await fetch('/api/leads/search?'+p);let d=await r.json();if(!r.ok)throw Error(d.error);leads.value=d.items||[];info.value=d.demo?'Демо-режим: добавь DGIS_API_KEY в .env для реального поиска.':`Найдено: ${leads.value.length}`;}catch(e){error.value=e.message}finally{loading.value=false}}
async function checkSites(){checking.value=true;try{let r=await fetch('/api/leads/check-sites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:leads.value})});let d=await r.json();if(!r.ok)throw Error(d.error);leads.value=d.items}catch(e){error.value=e.message}finally{checking.value=false}}
async function message(x){generating.value=true;try{let r=await fetch('/api/messages/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lead:x})});let d=await r.json();if(!r.ok)throw Error(d.error);x.message=d.message;selected.value=x}catch(e){error.value=e.message}finally{generating.value=false}}
function score(x){let s=0;if(!x.website)s+=35;if(x.websiteCheck?.reachable===false)s+=20;if(x.phone)s+=10;if(x.social)s+=10;if((x.rating||0)>=4.5)s+=10;if((x.reviews||0)>=20)s+=10;return Math.min(100,s)}
function status(x){if(!x.website)return 'Нет сайта';if(x.websiteCheck?.reachable===false)return 'Сайт недоступен';if(x.websiteCheck?.reachable)return 'Сайт работает';return 'Не проверен'}
function csv(){let h=['Бизнес','Категория','Сайт','Телефон','Адрес','Рейтинг','Отзывы','Приоритет','Статус','Сообщение'];let rows=shown.value.map(x=>[x.name,x.category,x.website||'',x.phone||'',x.address||'',x.rating||'',x.reviews||'',score(x),status(x),x.message||'']);let s=[h,...rows].map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+s],{type:'text/csv;charset=utf-8'}));a.download='client-leads.csv';a.click()}
</script>
<template><main><header><div><small>WEB DESIGN / FRONTEND</small><h1>Client Finder</h1><p>2ГИС → поиск → проверка сайтов → персональные сообщения</p></div><b>Алматы · KZ</b></header><section class="panel controls"><label>Город<input v-model="city"></label><label>Категория<select v-model="category"><option v-for="c in cats">{{c}}</option></select></label><label>Мин. рейтинг<input type="number" min="0" max="5" step=".1" v-model="minRating"></label><label>Количество<input type="number" min="1" max="100" v-model="limit"></label><label class="check"><input type="checkbox" v-model="onlyNoSite"> Только без сайта</label><button class="primary" @click="search" :disabled="loading">{{loading?'Ищу...':'Найти лидов'}}</button></section><div v-if="info" class="info">{{info}}</div><div v-if="error" class="error">{{error}}</div><section v-if="leads.length" class="actions"><button @click="checkSites" :disabled="checking">{{checking?'Проверяю...':'Автоматически проверить сайты'}}</button><button @click="csv">Экспорт CSV</button><span>{{shown.length}} лидов</span></section><section class="layout"><div class="panel table"><table><thead><tr><th>Бизнес</th><th>Категория</th><th>Сайт</th><th>Рейтинг</th><th>Приоритет</th><th>Статус</th><th></th></tr></thead><tbody><tr v-for="x in shown" :key="x.id"><td><strong>{{x.name}}</strong><small>{{x.address}}</small></td><td>{{x.category}}</td><td><a v-if="x.website" :href="x.website" target="_blank">{{x.website}}</a><span v-else>—</span></td><td>{{x.rating||'—'}} <small v-if="x.reviews">({{x.reviews}})</small></td><td><em>{{score(x)}}</em></td><td>{{status(x)}}</td><td><button class="small" @click="message(x)" :disabled="generating">Сообщение</button></td></tr></tbody></table><div v-if="!leads.length" class="empty">Выбери категорию и нажми «Найти лидов».</div></div><aside v-if="selected" class="panel detail"><button class="close" @click="selected=null">×</button><small>ПЕРСОНАЛЬНОЕ ОБРАЩЕНИЕ</small><h2>{{selected.name}}</h2><p>{{selected.category}} · {{selected.address}}</p><textarea v-model="selected.message" rows="13"></textarea><button class="primary" @click="navigator.clipboard.writeText(selected.message)">Копировать</button></aside></section></main></template>
